// Copyright 2026 RegaliumOS™.
// SPDX-License-Identifier: Apache-2.0

// Command schemadrift verifies that the FlatBuffers poll-cycle schema still
// mirrors the protobuf messages it claims to mirror.
//
// # Why this exists
//
// The .proto tree is the source of truth for the OSDP domain. A small subset of
// it -- the payloads exchanged on every poll, thousands of times a minute -- is
// additionally expressed in FlatBuffers because decoding those on the hot path
// should not allocate. Two schemas describing one thing is a standing invitation
// to drift, and drift here is not a compile error: it is a field that silently
// decodes to the wrong offset on a live access-control bus.
//
// # What is checked
//
// Three artefacts must agree, not two. The .proto says what a field is and
// which number it holds. buffers.lock says which target ordinal that number was
// given, and is committed precisely so a rebuild cannot quietly move it. The
// .fbs says where the mirror actually put it. Any two agreeing while the third
// differs is the interesting case, because it says which one moved.
//
// # Declaring a mirror
//
// A generated schema carries the declaration its generator wrote:
//
//	// source: osdp/event/v1/payloads.proto
//
// A hand-written one names the message above the table:
//
//	/// mirrors: osdp.event.v1.CardRead
//	table CardRead { ... }
//
// Either way the claim travels in the file it is a claim about, so the two
// cannot come apart on their own.
package main

import (
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	fbsRoot := flag.String("fbs", "protobuf/generated/flatbuffers",
		"root of the FlatBuffers schema tree")
	protoRoot := flag.String("proto", "protobuf", "root of the protobuf module")
	ledgerPath := flag.String("ledger", "buffers.lock", "the ordinal ledger")
	flag.Parse()

	if err := run(*fbsRoot, *protoRoot, *ledgerPath); err != nil {
		fmt.Fprintf(os.Stderr, "schemadrift: %v\n", err)
		os.Exit(1)
	}
}

func run(fbsRoot, protoRoot, ledgerPath string) error {
	schemas, err := findSchemas(fbsRoot)
	if err != nil {
		return err
	}

	// The guard that matters. A gate which reports success because it could not
	// find the tree it was meant to check is worse than no gate, because it is
	// believed -- and this repository has shipped that mistake once already.
	if len(schemas) == 0 {
		fmt.Fprint(os.Stderr,
			"  This gate verifies mirrored tables. Finding none means it verified\n"+
				"  nothing, which is a failure and not a pass. Check the path.\n")
		return fmt.Errorf("no .fbs schemas found under %q", fbsRoot)
	}

	ledger, err := ParseLedger(ledgerPath)
	if err != nil {
		return fmt.Errorf("reading the ordinal ledger: %w", err)
	}

	var drifts []Drift
	var checked int
	for _, path := range schemas {
		n, found, err := verify(path, protoRoot, ledger)
		if err != nil {
			return err
		}
		checked += n
		drifts = append(drifts, found...)
	}

	if checked == 0 {
		fmt.Fprint(os.Stderr,
			"  Every .fbs here mirrors a .proto. One that names no source is either\n"+
				"  hand-written without a `mirrors:` comment, or generated by something\n"+
				"  that did not record where it came from.\n")
		return fmt.Errorf("%d schema file(s) under %q declare no mirrored tables",
			len(schemas), fbsRoot)
	}

	if len(drifts) > 0 {
		fmt.Fprintf(os.Stderr, "schemadrift: %d disagreement(s) between the schemas:\n\n", len(drifts))
		for _, d := range drifts {
			fmt.Fprintf(os.Stderr, "  %s\n", d)
		}
		fmt.Fprintf(os.Stderr, "\n  Edit the .proto and regenerate; never edit a mirror by hand.\n")
		os.Exit(1)
	}

	fmt.Printf("schemadrift: %d mirrored table(s) across %d schema(s) agree with\n",
		checked, len(schemas))
	fmt.Printf("  their .proto and with %s.\n", ledgerPath)
	return nil
}

// findSchemas lists every .fbs under root.
func findSchemas(root string) ([]string, error) {
	var out []string

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(path, ".fbs") {
			out = append(out, path)
		}
		return nil
	})
	if os.IsNotExist(err) {
		// Reported by the caller as "found none", which is the failure it is.
		return nil, nil
	}
	return out, err
}
